### ISSUE TITLE
Python 3.5.1  Not a valid Win32 Application?

### ISSUE THREAD

**Issue by Zachman61** [SexualRhinoceros/MusicBot#1]
So upon running fixnupdate.bat successfully and then trying to run via runbot.bat, I get this error:

    F:\DiscordMusicBot>python MusicBot.py
    Traceback (most recent call last):
      File "MusicBot.py", line 10, in <module>
        discord.opus.load_opus('libopus-0.dll')
      File "C:\Python35\lib\site-packages\discord\opus.py", line 113, in load_opus
        _lib = libopus_loader(name)
      File "C:\Python35\lib\site-packages\discord\opus.py", line 57, in libopus_loader
        lib = ctypes.cdll.LoadLibrary(name)
      File "C:\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
        return self._dlltype(name)
      File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application

Any ideas?

**Comment by SexualRhinoceros** [comment]
download x86 python and retry

**Comment by Zachman61** [comment]
After downloading the x86 version (after uninstalling the x64) I still get the same error.
